server:
  port: 4444
  
spring:
  application:
    name: sail-service
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: root
  jpa: 
    properties:
      hibernate:
        show_sql: true
        format_sql: true
